### ISSUE TITLE
Cannot send session cache limiter - headers already sent

### ISSUE THREAD

**Issue by redbar0n** [nekojira/wp-php-console#11]
Wordpress WPMU: 4.2.2
Theme: Twenty Fifteen
PHP: 5.4.40
All other plugins deactivated.

This error occurs at the bottom of the page:

`Cannot send session cache limiter - headers already sent (output started at /home/odio/public_html/wp-includes/functions.php:3282) in /home/odio/public_html/wp-content/plugins/wp-php-console/vendor/php-console/php-console/src/PhpConsole/Storage/Session.php on line 25`

In the Settings menu, the WP PHP Console isn't there, but the above error message is at the bottom of the page.

**Comment by redbar0n** [comment]
Even tried deactivating the theme Twenty Fifteen.

**Comment by nekojira** [comment]
Hello @redbar0n 

I'm not sure yet where the problem could be. I did a little commit just now but I doubt it can fix your issue.

Are you running WordPress in multisite? I admit I never tested WP PHP Console in multisite. But perhaps we can figure out. Have you activated the plugin as network plugin or locally in one of the blogs?

**Comment by redbar0n** [comment]
Hi! Yeah, I'm running in Multisite.

I've been running into the "headers not set" problem with the own plugin I'm developing. It's probably due to some echo's or something in the code.

Maybe either of these can help:
http://stackoverflow.com/a/8028987/380607
http://wordpress.stackexchange.com/questions/105453/getting-headers-already-sent-error-from-plugin
http://wordpress.stackexchange.com/questions/132288/getting-redirect-to-happen-before-header-output

**Comment by redbar0n** [comment]
From looking at the code, it seems it's the session_start() that does it. That first link I gave should tell you why, and perhaps this might help:
http://stackoverflow.com/questions/712326/why-cant-i-use-session-start-in-my-php-script-it-says-headers-are-already-se?rq=1

**Comment by nekojira** [comment]
Ah so there is at least one more plugin active which maybe is instantiated before WP Php Console.

headers not sent could be due to multiple issues, some are a bit strange

for example, does any of your php files end with `?>` php closure tag? if yes, please remove them (the very last `?>` in your code as long as there's nothing after it 

also, if you are developing a plugin, make sure you are running in `WP_DEBUG` mode (it's a constant you can set in `wp-config.php`) and turn all the PHP errors on (you should do that anyway when using PHP Console, so your errors will be printed there for your convenience)

**Comment by nekojira** [comment]
some explaination about the final `?>` tag http://stackoverflow.com/questions/4410704/why-would-one-omit-the-close-tag

**Comment by redbar0n** [comment]
I had deactivated all other plugins, as initially stated. Even my own plugin. Error still occurs.

No closing ?> tags anywhere to my knowledge.

Not sure what's in the /home/odio/public_html/wp-includes/functions.php:3282 file, but it should be pretty standard WPMU stuff.

No other of my plugins give this error, when I try to separately activate them, so I doubt the error lies in the aforementioned file.

I think it has to do with having to wrap session_start, or maybe check if the session is already started before you try to start it, because in that case you might not need to start it.

**Comment by nekojira** [comment]
oh ok, sorry I got it wrong and thought you were developing a plugin which was active

it could be something specific to multisite or PHP Console library which my plugin depends upon - or I need to make adjustments for a multisite-specific context but I'm not sure yet what would that be

`functions.php` mentioned in your error is a WordPress functions library and is not multisite specific (wp-includes contains the WordPress application essentially)

your installation is complaining about this function below from WordPress core, but it's likely the error is produced with the interaction with PHP Console library 

```
/**
 * Flush all output buffers for PHP 5.2.
 *
 * Make sure all output buffers are flushed before our singletons are destroyed.
 *
 * @since 2.2.0
 */
function wp_ob_end_flush_all() {
	$levels = ob_get_level();
	for ($i=0; $i<$levels; $i++)
		ob_end_flush();
}
```

if we want to rule out a few things, would you mind giving a spin to the plugin on the very same machine but in a non-multisite context? if the error persist, the problem is probably not multisite

**Comment by redbar0n** [comment]
Yes, `ob_end_flush();` will output the headers to the page, so what the error message says is that it already output headers to the page in that wordpress core functions file, and you're trying to do the same thing again with `session_start();`

Are you sure you're not seeing the same error at the bottom of your admin plugins page? 

Hm, maybe it has to do with the wordpress version. That they added the ob_end_flush() at that line there.

Maybe it would help if you wrapped your plugin in an output buffer... I don't know..

I don't have the opportunity to try a regular wordpress install on the same server, I'm afraid. Not until maybe over the summer. It's another guy who has root control over it, and he's on vacation, I'm afraid. :/

**Comment by nekojira** [comment]
No I don't see the error, in one live and one local machine. 

You too are running WordPress 4.2.2 so it's not an old version (and still I don't think it would make a difference).

WordPress has a lot of legacy code in it, mostly for backwards compatibility - but I don't think the problem is there really, because this error is specific to your installation, it's just a bit hard to replicate. 

Just let me think a bit about it. If we can't come with a solution, might as well ask Sergey Barbushin, the original author of PHP Console (which is not WordPress specific), he might have a clue if he has seen this error before.

**Comment by HRoger** [comment]
Hi there! I had the same issue : Cannot send session cache limiter - headers already sent.

In my case wp-php-console is not compatible  with debug plugin "query monitor". So I deactivated the "query monitor plugin" and works now. 

I used to work with the "debug bar" plugin, so I tried to install it but wont work with wp-php-console addon as well.

It would be nice if wp-php-console was compatible with "query monitor" or the "debug bar".

**Comment by nekojira** [comment]
Hi @HRoger I understand. I think this might have to do with inner workings of WordPress and PHP Console as a plugin. Plugins in WordPress do not follow really a dependency or hierarchy and as far as I know they don't follow an order when being loaded in WordPress (I think if there's an order it's alphabetical). I don't plan to rename WP Php Console to 'AAAA WP Php Console' but perhaps there's a better solution to when having WP Php Console to load and maybe that would change something.

**Comment by nekojira** [comment]
I just thought, maybe it's worth trying to wrap WP Php Console main library with an action. You may try in  wp-php-console.php this:

```
/**
 * Include PhpConsole server library.
 * @link https://github.com/barbushin/php-console
 * Copyright (c) 2011-2013 by Barbushin Sergey <barbushin@gmail.com>.
 */
require_once 'vendor/autoload.php';
/**
 * The main class of this plugin.
 */
require_once 'lib/class-wp-php-console.php';
```

With something like this:

```
add_action( 'plugins_loaded', 'test' );

function test() {
require_once 'vendor/autoload.php';
require_once 'lib/class-wp-php-console.php';
}

```

Or maybe we can try another hook, I need to check.

**Comment by HRoger** [comment]
Hi,

Sorry, no luck. I tried:
//require_once plugin_dir_path( __FILE__ ) . 'vendor/autoload.php';
/**
 * The main class of this plugin.
 */
//require_once plugin_dir_path( __FILE__ ) . 'lib/class-wp-php-console.php';

add_action( 'plugins_loaded', 'test' );

function test() {
	require_once  plugin_dir_path( __FILE__ ) . 'vendor/autoload.php';
	require_once  plugin_dir_path( __FILE__ ) . 'lib/class-wp-php-console.php';
}

**Comment by nekojira** [comment]
try again using the most updated version from here on GitHub - I have made the class to instantiate when you require the file

**Comment by HRoger** [comment]
Ok. Thank you for your reply.  I tried but it didnt't work. Still conflicts with other debug plugins. 
For example, please try to install "query monitor" plugin
https://github.com/johnbillion/query-monitor
That's when the error " Cannot send session cache limiter - headers already sent" appears.

**Comment by nekojira** [comment]
Hi @HRoger I just installed the plugin but it works on my machine - both plugins do.
Do you have other plugins active? Can you deactivate those and use the default TwentyFourteen theme?  Are you also on Multisite like @redbar0n ? What version of PHP are you using? I wonder if this has to do with some particular configuration rather than other plugins.

**Comment by nekojira** [comment]
opened ticket on PhpConsole as well https://github.com/barbushin/php-console/issues/88

**Comment by nekojira** [comment]
everyone, download and try the latest commit in master branch, probably the issue is fixed, please let me know so I can issue a new release and update the plugin on WordPress.org svn as well

**Comment by HRoger** [comment]
Hi there,

Thanks again for your attention. I am not using multisite. I tried with TwentyFourteen and TwentyFifteen as well. In this case the "cannot send session cache limiter" appears at the bottom of the admin page.
I tried also to install the last branch commit but unfortunately it throws the following errors:
```text
Fatal error: Uncaught exception 'Exception' with message 'Unable to write file /tmp/pc.data' in wp-content\plugins\wp-php-console\vendor\php-console\php-console\src\PhpConsole\Storage\File.php on line 28

Warning: file_put_contents(/tmp/pc.data): failed to open stream: No such file or directory in wp-content\plugins\wp-php-console\vendor\php-console\php-console\src\PhpConsole\Storage\File.php on line 27
```

**Comment by nekojira** [comment]
you need to make sure you can write that directory - probably you don't have rights

if you have a terminal you can use chmod, if you are by ftp you can change permissions for wp-php-console and it's contents

I will investigate if there's a workaround from PHP for this, or maybe will try to point the target file to /uploads dir which should be normally writeable

**Comment by HRoger** [comment]
Hi there,
I'm using a pc with PHP5.6/NGINX 1.9 and I have permission to write to the directory.  I also tried to create the tmp/pc.data and set permission to the directory. But didn't work.
Thanks

**Comment by nekojira** [comment]
Yeah I'm trying this now in my class file in lib:

```
$upload_dir = wp_upload_dir();
		$phpcdir = $upload_dir['basedir'] . '/php-console/';
		$make_dir = wp_mkdir_p( $phpcdir );
		if ( $make_dir === true ) {
			PhpConsole\Connector::setPostponeStorage( new PhpConsole\Storage\File( $phpcdir . 'pc.data' ) );
		}
```

but it's not working either as it's PHP Console that refuses to write there this time, I'm talking with PHP Console library author to come up with a solution

**Comment by nekojira** [comment]
Hi @HRoger do you mind checking again now with the latest version here on github?

thanks

**Comment by HRoger** [comment]
Hi nekojira,

This one rocks! No errors anymore and page loads even faster now!

"Query monitor" and "debug bar" are working properly now.

Thank you very much

Best regards

**Comment by nekojira** [comment]
ok cool - if you like the plugin you can star or review it over [wordpress.org](https://wordpress.org/plugins/wp-php-console/) - I will push later the latest update to wp svn

**Comment by nekojira** [comment]
oh you just had :) thanks
